import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  title = 'Next.js',
}: {
  children: React.ReactNode
  title: string
}) {
  return (
    <html lang='en'>
      <title>{title}</title>

      <body className='bg-gray-900 h-screen flex flex-col dark'> {children}</body>
    </html>
  )
}
