### Solicitação de Direções Sem Waypoints
GET http://localhost:3333/directions?originId=ChIJqQMLQ1mrVAcRMZALfnM8ilA&destinationId=ChIJx332MqJTqwARQk4COuTDx_8

### Solicitação de Direções Com Um Waypoint
GET http://localhost:3333/directions?originId=ChIJqQMLQ1mrVAcRMZALfnM8ilA&destinationId=ChIJx332MqJTqwARQk4COuTDx_8&waypoints[]=ChIJN1t_tDeuEmsRUsoyG83frY4

### Solicitação de Direções Com Vários Waypoints
GET http://localhost:3333/directions?originId=ChIJqQMLQ1mrVAcRMZALfnM8ilA&destinationId=ChIJx332MqJTqwARQk4COuTDx_8&waypoints[]=ChIJN1t_tDeuEmsRUsoyG83frY4&waypoints[]=ChIJJ3SpfQsLlVQRkYXR9ua5Nhw

### Criar Rota Sem Waypoints
POST http://localhost:3333/routes
Content-Type: application/json

{
  "name": "Rota com 1 Waypoint",
  "sourceId": "ChIJqQMLQ1mrVAcRMZALfnM8ilA",
  "destinationId": "ChIJx332MqJTqwARQk4COuTDx_8",
  "distance": 7145,
  "duration": 841,
  "polyline": "dk~dB`cvjGvBk@h@OdAfEp@jChCs@`EiA~JuC\\KRMl@MfBYrBMVAVJ`@Tb@\\P^@rAEhB?d@B`@Ld@Nb@d@r@dArAd@j@j@`@ZP~Ab@hBp@ZVRb@f@xA^`AXVn@b@jB~@hDtAr@b@RRTZVx@x@fGJ|@Pv@d@`ArAjBj@x@d@dAFPLn@Db@@p@Et@WfBy@zEOhB@rAP`BXdA\\x@^l@|AzBxAhB`@f@f@Xp@Vl@N|AL`ADp@Nr@Vp@f@z@v@dDpCjA`AtAlAtC~BtAn@`ATv@Nv@FbB?fBU`Cq@bJqC`HuB`EuAN@\\Ff@ZZXzBxAtCn@hARnBT|HfAbGz@zRrCfRtC|ItAtG`Af@PHFRVLb@HNz@d@rFjDjGtDjAp@pD|Bv@VVx@LR?HbCiA"
}
### Criar Rota Com Um Waypoint
POST http://localhost:3333/routes
Content-Type: application/json



### Criar Rota Com Vários Waypoints
POST http://localhost:3333/routes
Content-Type: application/json

{
  "name": "Rota Simplificada com Waypoints",
  "sourceId": "ChIJqQMLQ1mrVAcRMZALfnM8ilA",
  "destinationId": "ChIJx332MqJTqwARQk4COuTDx_8",
  "distance": 7145,
  "duration": 841,
  "polyline": "dk~dB`cvjGvBk@h@OdAfEp@jChCs@`EiA~JuC\\KRMl@MfBYrBMVAVJ`@Tb@\\P^@rAEhB?d@B`@Ld@Nb@d@r@dArAd@j@j@`@ZP~Ab@hBp@ZVRb@f@xA^`AXVn@b@jB~@hDtAr@b@RRTZVx@x@fGJ|@Pv@d@`ArAjBj@x@d@dAFPLn@Db@@p@Et@WfBy@zEOhB@rAP`BXdA\\x@^l@|AzBxAhB`@f@f@Xp@Vl@N|AL`ADp@Nr@Vp@f@z@v@dDpCjA`AtAlAtC~BtAn@`ATv@Nv@FbB?fBU`Cq@bJqC`HuB`EuAN@\\Ff@ZZXzBxAtCn@hARnBT|HfAbGz@zRrCfRtC|ItAtG`Af@PHFRVLb@HNz@d@rFjDjGtDjAp@pD|Bv@VVx@LR?HbCiA"
}
