version: '3'

services:
  mysql-go: 
    image: mysql:8
    container_name: mysql-go
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routes
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    
# CREATE TABLE routes (id VARCHAR(36) PRIMARY KEY,name VARCHAR(255) NOT NULL,distance FLOAT NOT NULL,status VARCHAR(255) NOT NULL, freight_price FLOAT,started_at DATETIME,finished_at DATETIME);