version: '3'

services:
  mysql-go: 
    image: mysql:8
    container_name: mysql-go
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routes
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./.docker/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./.docker/grafana_data:/var/lib/grafana
# CREATE TABLE routes (id VARCHAR(36) PRIMARY KEY,name VARCHAR(255) NOT NULL,distance FLOAT NOT NULL,status VARCHAR(255) NOT NULL, freight_price FLOAT,started_at DATETIME,finished_at DATETIME);